apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{ include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "helm.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{ toYaml .Values.startupProbe | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PG_HOST
              value: {{ .Values.config.database.host }}
            - name: PG_PORT
              value: {{ .Values.config.database.port | quote }}
            - name: PG_USER
              value: {{ .Values.config.database.user }}
            - name: PG_PASSWORD
              value: {{ .Values.config.database.password }}
            - name: PG_DB
              value: {{ .Values.config.database.db }}

            - name: MAIL_HOST
              value: {{ .Values.config.mail.host }}
            - name: MAIL_PORT
              value: {{ .Values.config.mail.port | quote }}
            - name: MAIL_USER
              value: {{ .Values.config.mail.user }}
            - name: MAIL_PASSWORD
              value: {{ .Values.config.mail.password }}
            - name: MAIL_FROM
              value: {{ .Values.config.mail.from }}

            - name: APP_CONFIRMATION_LINK
              value: {{ .Values.config.app_confirmation_link }}
      {{- with .Values.volumes }}
      volumes:
        {{ toYaml . | nindent 8 }}
      {{- end }}
