apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-db-migration-job
  labels:
    {{ include "helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-upgrade,pre-install"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  backoffLimit: 6
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        name: {{ include "helm.fullname" . }}-db-migration-job
        {{ include "helm.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "helm.fullname" . }}-db-migration
          image: {{ .Values.migrations.repository }}:{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LIQUIBASE_URL
              value: "jdbc:postgresql://{{ .Values.config.database.host }}:{{ .Values.config.database.port }}/{{ .Values.config.database.db }}"
            - name: LIQUIBASE_USERNAME
              value: {{ .Values.config.database.user }}
            - name: LIQUIBASE_PASSWORD
              value: {{ .Values.config.database.password }}
