replicaCount: 1

version: ""

image:
  repository: ghcr.io/lysmux/web4-backend

migrations:
  repository: ghcr.io/lysmux/web4-backend-migrations

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/q/metrics"
  prometheus.io/port: "8080"
podLabels: {}

livenessProbe:
  httpGet:
    path: /alive
    port: 8080
readinessProbe:
  httpGet:
    path: /alive
    port: 8080
startupProbe:
  httpGet:
    path: /alive
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

config:
  database:
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    user: web4
    password:
    db: web4

  mail:
    host: mail.lysmux.dev
    port: 587
    user: web@lysmux.dev
    password:
    from: web@lysmux.dev

  app_confirmation_link: https://web4.lysmux.dev/auth/confirmation/%s